import { Camera, Alert, VehicleSighting, WatchlistEntry, Detection, DashboardSummary, VehicleRoutePoint } from '../types';
import { generateAhmedabadEvidenceFrame } from './ahmedabad-evidence';

// Helper to create reliable Ahmedabad surveillance evidence frames with Indian vehicle and HSRP number plate OCR
export function generateEvidenceFrameSvg(
  plate: string,
  cameraName: string,
  timestamp: string,
  vehicleType: string = 'Sedan',
  colorHex: string = '#3b82f6',
  isAlert: boolean = false
): string {
  return generateAhmedabadEvidenceFrame({
    plate,
    cameraName,
    location: `${cameraName}, Ahmedabad, Gujarat`,
    timestamp,
    vehicleType,
    vehicleColor: colorHex,
    isAlert,
    matchType: isAlert ? 'exact' : 'none',
    detectionConfidence: 96.4,
    ocrConfidence: 94.8,
    aggregationAgreement: '13/16 (81.2%)',
    speedKmh: 58,
  });
}

export const INITIAL_CAMERAS: Camera[] = [
  {
    id: 'CAM-01',
    name: 'Ring Road West Gate',
    location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
    latitude: 23.0225,
    longitude: 72.5714,
    status: 'online',
    vendor: 'Axis Communications Q1656-LE',
    lastHeartbeat: 'Just now (1s ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam01',
    uptime: '99.8%',
    fps: 30,
    resolution: '3840x2160 (4K UHD)',
    totalDetections: 4820,
    activeAlertsCount: 2,
  },
  {
    id: 'CAM-02',
    name: 'Express Highway Toll Plaza',
    location: 'National Highway 48 Exit Toll, Ahmedabad',
    latitude: 23.0338,
    longitude: 72.5850,
    status: 'online',
    vendor: 'Hikvision DeepinView ANPR-i7',
    lastHeartbeat: 'Just now (2s ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam02',
    uptime: '99.9%',
    fps: 60,
    resolution: '2560x1440 (2K)',
    totalDetections: 6210,
    activeAlertsCount: 1,
  },
  {
    id: 'CAM-03',
    name: 'City Central Flyover',
    location: 'Paldi Cross Road Overbridge, Ahmedabad',
    latitude: 23.0450,
    longitude: 72.5600,
    status: 'online',
    vendor: 'Hanwha Techwin Wisenet XNV-8081Z',
    lastHeartbeat: 'Just now (4s ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam03',
    uptime: '99.4%',
    fps: 30,
    resolution: '3840x2160 (4K UHD)',
    totalDetections: 3940,
    activeAlertsCount: 1,
  },
  {
    id: 'CAM-04',
    name: 'Suburb Industrial Bypass',
    location: 'Sanand Industrial Estate Approach, Ahmedabad',
    latitude: 23.0550,
    longitude: 72.5950,
    status: 'warning',
    vendor: 'Dahua Technology ITC431-RW1F',
    lastHeartbeat: '48s ago (Packet Jitter)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam04',
    uptime: '96.2%',
    fps: 22,
    resolution: '1920x1080 (1080p)',
    totalDetections: 2150,
    activeAlertsCount: 1,
  },
  {
    id: 'CAM-05',
    name: 'Riverfront Promenade North',
    location: 'Sabarmati Riverfront West Bank, Ahmedabad',
    latitude: 23.0300,
    longitude: 72.5780,
    status: 'online',
    vendor: 'Bosch DINION IP thermal 8000',
    lastHeartbeat: 'Just now (1s ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam05',
    uptime: '99.7%',
    fps: 30,
    resolution: '3840x2160 (4K UHD)',
    totalDetections: 3200,
    activeAlertsCount: 0,
  },
  {
    id: 'CAM-06',
    name: 'Metro Station Terminal 3',
    location: 'Kalupur Central Railway & Metro Gate, Ahmedabad',
    latitude: 23.0150,
    longitude: 72.5450,
    status: 'offline',
    vendor: 'Uniview Prime Ultra IPC264E',
    lastHeartbeat: 'Offline (18m ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam06',
    uptime: '91.0%',
    fps: 0,
    resolution: '1920x1080 (1080p)',
    totalDetections: 1420,
    activeAlertsCount: 0,
  },
  {
    id: 'CAM-07',
    name: 'Airport Cargo Boulevard',
    location: 'SVPI Airport Terminal 2 Connector, Ahmedabad',
    latitude: 23.0700,
    longitude: 72.6300,
    status: 'online',
    vendor: 'Axis Communications Q1656-LE',
    lastHeartbeat: 'Just now (1s ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam07',
    uptime: '99.9%',
    fps: 60,
    resolution: '3840x2160 (4K UHD)',
    totalDetections: 5120,
    activeAlertsCount: 0,
  },
  {
    id: 'CAM-08',
    name: 'University Circle Outer',
    location: 'Gujarat University Navrangpura Circle, Ahmedabad',
    latitude: 23.0380,
    longitude: 72.5400,
    status: 'online',
    vendor: 'Hikvision DeepinView ANPR-i7',
    lastHeartbeat: 'Just now (3s ago)',
    streamUrl: 'rtsp://anpr-edge.city.net/stream/cam08',
    uptime: '98.9%',
    fps: 30,
    resolution: '2560x1440 (2K)',
    totalDetections: 4180,
    activeAlertsCount: 0,
  },
];

export const INITIAL_WATCHLIST: WatchlistEntry[] = [
  {
    id: 'WL-101',
    plateNumber: 'GJ05CD5678',
    category: 'Stolen Vehicle',
    priority: 'high',
    reason: 'Reported stolen black luxury sedan; suspect involved in interstate robbery FIR #892/2026',
    caseId: 'CASE-GJ-2026-892',
    dateAdded: '10 Sept 2026, 08:30 PM',
    status: 'active',
    lastSighting: {
      timestamp: '11 Sept 2026, 11:03 AM',
      cameraName: 'City Central Flyover',
      location: 'Paldi Cross Road Overbridge, Ahmedabad',
    },
    ownerNotes: 'Vehicle flagged with immediate intercept instruction.',
  },
  {
    id: 'WL-102',
    plateNumber: 'GJ01AB1234',
    category: 'Wanted Suspect',
    priority: 'high',
    reason: 'Registered vehicle associated with financial fraud fugitive under active non-bailable warrant',
    caseId: 'CASE-GJ-2026-441',
    dateAdded: '09 Sept 2026, 11:15 AM',
    status: 'active',
    lastSighting: {
      timestamp: '11 Sept 2026, 10:45 AM',
      cameraName: 'Ring Road West Gate',
      location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
    },
    ownerNotes: 'Observe and report direction of travel; do not provoke single-unit confrontation.',
  },
  {
    id: 'WL-103',
    plateNumber: 'DL08CN4521',
    category: 'Traffic Violation',
    priority: 'medium',
    reason: 'Multiple unpaid high-speed intersection infractions and reckless lane hopping violations',
    caseId: 'VIOL-DL-2026-109',
    dateAdded: '07 Sept 2026, 04:20 PM',
    status: 'active',
    lastSighting: {
      timestamp: '11 Sept 2026, 09:12 AM',
      cameraName: 'Express Highway Toll Plaza',
      location: 'National Highway 48 Exit Toll, Ahmedabad',
    },
  },
  {
    id: 'WL-104',
    plateNumber: 'GJ27AA9901',
    category: 'High Risk',
    priority: 'high',
    reason: 'Suspect vehicle spotted near industrial restricted perimeter without valid gate pass',
    caseId: 'SEC-GJ-2026-033',
    dateAdded: '08 Sept 2026, 02:00 PM',
    status: 'active',
    lastSighting: {
      timestamp: '11 Sept 2026, 08:50 AM',
      cameraName: 'Suburb Industrial Bypass',
      location: 'Sanand Industrial Estate Approach, Ahmedabad',
    },
  },
  {
    id: 'WL-105',
    plateNumber: 'MH12PQ3456',
    category: 'Unregistered',
    priority: 'low',
    reason: 'Defaced plate and forged registration sticker reported during routine checkpoint',
    caseId: 'CHKP-MH-2026-778',
    dateAdded: '05 Sept 2026, 10:00 AM',
    status: 'disabled',
    ownerNotes: 'Entry cleared after physical inspection in Surat.',
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-901',
    type: 'Watchlist Hit (Stolen Vehicle)',
    priority: 'high',
    plateNumber: 'GJ05CD5678',
    cameraId: 'CAM-03',
    cameraName: 'City Central Flyover',
    location: 'Paldi Cross Road Overbridge, Ahmedabad',
    timestamp: '11 Sept 2026, 11:03 AM',
    reason: 'Matched Watchlist: Stolen vehicle FIR #892/2026. Suspect moving South toward Riverfront.',
    status: 'new',
    confidence: 96,
    detectionConfidence: 97,
    ocrConfidence: 95,
    caseId: 'CASE-GJ-2026-892',
    evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'City Central Flyover', '11 Sept 2026, 11:03 AM', 'Sedan', '#1e293b', true),
    notes: 'Auto-triggered by ANPR Pipeline v4.2 edge model.',
  },
  {
    id: 'ALT-902',
    type: 'Watchlist Hit (Wanted Suspect)',
    priority: 'high',
    plateNumber: 'GJ01AB1234',
    cameraId: 'CAM-01',
    cameraName: 'Ring Road West Gate',
    location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
    timestamp: '11 Sept 2026, 10:45 AM',
    reason: 'Matched Watchlist: High Priority Warrant CASE-GJ-2026-441. Vehicle detected eastbound.',
    status: 'under_review',
    confidence: 94,
    detectionConfidence: 96,
    ocrConfidence: 93,
    caseId: 'CASE-GJ-2026-441',
    evidenceUrl: generateEvidenceFrameSvg('GJ01AB1234', 'Ring Road West Gate', '11 Sept 2026, 10:45 AM', 'SUV', '#047857', true),
    reviewedBy: 'Officer V. Patel (ID #402)',
    reviewedAt: '11 Sept 2026, 10:48 AM',
    notes: 'Forwarded to Dispatch Unit 4 for surveillance perimeter.',
  },
  {
    id: 'ALT-903',
    type: 'Perimeter Intrusion Alert',
    priority: 'high',
    plateNumber: 'GJ27AA9901',
    cameraId: 'CAM-04',
    cameraName: 'Suburb Industrial Bypass',
    location: 'Sanand Industrial Estate Approach, Ahmedabad',
    timestamp: '11 Sept 2026, 08:50 AM',
    reason: 'Flagged vehicle spotted in restricted cargo approach route without authorization RFID.',
    status: 'confirmed',
    confidence: 91,
    detectionConfidence: 94,
    ocrConfidence: 89,
    caseId: 'SEC-GJ-2026-033',
    evidenceUrl: generateEvidenceFrameSvg('GJ27AA9901', 'Suburb Industrial Bypass', '11 Sept 2026, 08:50 AM', 'Truck', '#b91c1c', true),
    reviewedBy: 'Security Lead K. Desai',
    reviewedAt: '11 Sept 2026, 09:05 AM',
  },
  {
    id: 'ALT-904',
    type: 'Repeat Speeding Infraction',
    priority: 'medium',
    plateNumber: 'DL08CN4521',
    cameraId: 'CAM-02',
    cameraName: 'Express Highway Toll Plaza',
    location: 'National Highway 48 Exit Toll, Ahmedabad',
    timestamp: '11 Sept 2026, 09:12 AM',
    reason: 'Vehicle clocked at 128 km/h in 80 km/h zone. Multiple pending citations.',
    status: 'new',
    confidence: 88,
    detectionConfidence: 92,
    ocrConfidence: 85,
    caseId: 'VIOL-DL-2026-109',
    evidenceUrl: generateEvidenceFrameSvg('DL08CN4521', 'Express Highway Toll Plaza', '11 Sept 2026, 09:12 AM', 'Hatchback', '#d97706', true),
  },
  {
    id: 'ALT-905',
    type: 'Plate Tampering / Glare Anomaly',
    priority: 'low',
    plateNumber: 'MH02DJ9090',
    cameraId: 'CAM-05',
    cameraName: 'Riverfront Promenade North',
    location: 'Sabarmati Riverfront West Bank, Ahmedabad',
    timestamp: '11 Sept 2026, 07:30 AM',
    reason: 'Retroreflective coating glare or dirty plate detected. OCR needed secondary alignment.',
    status: 'resolved',
    confidence: 72,
    detectionConfidence: 88,
    ocrConfidence: 68,
    evidenceUrl: generateEvidenceFrameSvg('MH02DJ9090', 'Riverfront Promenade North', '11 Sept 2026, 07:30 AM', 'Sedan', '#64748b', false),
    reviewedBy: 'Operator M. Joshi',
    reviewedAt: '11 Sept 2026, 08:00 AM',
    notes: 'Visual verification confirmed plate valid upon manual review. No infraction.',
  },
];

export const INITIAL_DETECTIONS: Detection[] = [
  {
    id: 'DET-5501',
    plateNumber: 'GJ05CD5678',
    normalizedPlate: 'GJ05CD5678',
    rawOcrText: 'GJ 05 CD 5678',
    cameraId: 'CAM-03',
    cameraName: 'City Central Flyover',
    location: 'Paldi Cross Road Overbridge, Ahmedabad',
    timestamp: '11 Sept 2026, 11:03 AM',
    detectionConfidence: 97,
    ocrConfidence: 95,
    trackingConfidence: 94,
    trackingId: 'TRK-44029',
    vehicleType: 'Luxury Sedan',
    vehicleColor: 'Black',
    isWatchlistMatch: true,
    watchlistReason: 'Reported Stolen Vehicle - Case FIR #892/2026',
    evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'City Central Flyover', '11 Sept 2026, 11:03 AM', 'Sedan', '#1e293b', true),
    boundingBox: { x: 200, y: 145, width: 240, height: 125 },
  },
  {
    id: 'DET-5502',
    plateNumber: 'GJ01AB1234',
    normalizedPlate: 'GJ01AB1234',
    rawOcrText: 'GJ01 AB 1234',
    cameraId: 'CAM-01',
    cameraName: 'Ring Road West Gate',
    location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
    timestamp: '11 Sept 2026, 10:45 AM',
    detectionConfidence: 96,
    ocrConfidence: 93,
    trackingConfidence: 95,
    trackingId: 'TRK-44012',
    vehicleType: 'Full-Size SUV',
    vehicleColor: 'Emerald Green',
    isWatchlistMatch: true,
    watchlistReason: 'Wanted Suspect Warrant CASE-GJ-2026-441',
    evidenceUrl: generateEvidenceFrameSvg('GJ01AB1234', 'Ring Road West Gate', '11 Sept 2026, 10:45 AM', 'SUV', '#047857', true),
    boundingBox: { x: 190, y: 140, width: 260, height: 135 },
  },
  {
    id: 'DET-5503',
    plateNumber: 'GJ05CD5678',
    normalizedPlate: 'GJ05CD5678',
    rawOcrText: 'GJ 05 CD 5678',
    cameraId: 'CAM-02',
    cameraName: 'Express Highway Toll Plaza',
    location: 'National Highway 48 Exit Toll, Ahmedabad',
    timestamp: '11 Sept 2026, 10:42 AM',
    detectionConfidence: 98,
    ocrConfidence: 96,
    trackingConfidence: 96,
    trackingId: 'TRK-44001',
    vehicleType: 'Luxury Sedan',
    vehicleColor: 'Black',
    isWatchlistMatch: true,
    watchlistReason: 'Reported Stolen Vehicle - Case FIR #892/2026',
    evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'Express Highway Toll Plaza', '11 Sept 2026, 10:42 AM', 'Sedan', '#1e293b', true),
    boundingBox: { x: 200, y: 145, width: 240, height: 125 },
  },
  {
    id: 'DET-5504',
    plateNumber: 'MH02DJ9090',
    normalizedPlate: 'MH02DJ9090',
    rawOcrText: 'MH-02 DJ 9090',
    cameraId: 'CAM-05',
    cameraName: 'Riverfront Promenade North',
    location: 'Sabarmati Riverfront West Bank, Ahmedabad',
    timestamp: '11 Sept 2026, 10:35 AM',
    detectionConfidence: 94,
    ocrConfidence: 91,
    trackingConfidence: 92,
    trackingId: 'TRK-43980',
    vehicleType: 'Compact Sedan',
    vehicleColor: 'Silver Grey',
    isWatchlistMatch: false,
    evidenceUrl: generateEvidenceFrameSvg('MH02DJ9090', 'Riverfront Promenade North', '11 Sept 2026, 10:35 AM', 'Sedan', '#64748b', false),
    boundingBox: { x: 210, y: 150, width: 220, height: 120 },
  },
  {
    id: 'DET-5505',
    plateNumber: 'GJ05CD5678',
    normalizedPlate: 'GJ05CD5678',
    rawOcrText: 'GJ05 CD 5678',
    cameraId: 'CAM-01',
    cameraName: 'Ring Road West Gate',
    location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
    timestamp: '11 Sept 2026, 10:24 AM',
    detectionConfidence: 95,
    ocrConfidence: 92,
    trackingConfidence: 91,
    trackingId: 'TRK-43940',
    vehicleType: 'Luxury Sedan',
    vehicleColor: 'Black',
    isWatchlistMatch: true,
    watchlistReason: 'Reported Stolen Vehicle - Case FIR #892/2026',
    evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'Ring Road West Gate', '11 Sept 2026, 10:24 AM', 'Sedan', '#1e293b', true),
    boundingBox: { x: 200, y: 145, width: 240, height: 125 },
  },
  {
    id: 'DET-5506',
    plateNumber: 'KA04ME7788',
    normalizedPlate: 'KA04ME7788',
    rawOcrText: 'KA 04 ME 7788',
    cameraId: 'CAM-08',
    cameraName: 'University Circle Outer',
    location: 'Gujarat University Navrangpura Circle, Ahmedabad',
    timestamp: '11 Sept 2026, 10:15 AM',
    detectionConfidence: 93,
    ocrConfidence: 89,
    trackingConfidence: 90,
    trackingId: 'TRK-43910',
    vehicleType: 'Hatchback',
    vehicleColor: 'White',
    isWatchlistMatch: false,
    evidenceUrl: generateEvidenceFrameSvg('KA04ME7788', 'University Circle Outer', '11 Sept 2026, 10:15 AM', 'Hatchback', '#f8fafc', false),
    boundingBox: { x: 210, y: 155, width: 220, height: 115 },
  },
  {
    id: 'DET-5507',
    plateNumber: 'GJ27AA9901',
    normalizedPlate: 'GJ27AA9901',
    rawOcrText: 'GJ 27 AA 9901',
    cameraId: 'CAM-04',
    cameraName: 'Suburb Industrial Bypass',
    location: 'Sanand Industrial Estate Approach, Ahmedabad',
    timestamp: '11 Sept 2026, 08:50 AM',
    detectionConfidence: 94,
    ocrConfidence: 89,
    trackingConfidence: 91,
    trackingId: 'TRK-43750',
    vehicleType: 'Commercial Truck',
    vehicleColor: 'Dark Crimson',
    isWatchlistMatch: true,
    watchlistReason: 'Restricted Industrial Zone Perimeter Alert',
    evidenceUrl: generateEvidenceFrameSvg('GJ27AA9901', 'Suburb Industrial Bypass', '11 Sept 2026, 08:50 AM', 'Truck', '#b91c1c', true),
    boundingBox: { x: 170, y: 120, width: 300, height: 160 },
  },
];

// Sightings specific for multi-camera route tracking
export const SIGHTINGS_BY_PLATE: Record<string, VehicleSighting[]> = {
  'GJ05CD5678': [
    {
      id: 'SGT-01',
      plateNumber: 'GJ05CD5678',
      cameraId: 'CAM-01',
      cameraName: 'Ring Road West Gate',
      location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
      timestamp: '11 Sept 2026, 10:24 AM',
      detectionConfidence: 95,
      ocrConfidence: 92,
      trackingConfidence: 91,
      vehicleType: 'Luxury Sedan (Black)',
      speedKmh: 68,
      lane: 2,
      heading: 'Eastbound',
      evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'Ring Road West Gate', '11 Sept 2026, 10:24 AM', 'Sedan', '#1e293b', true),
    },
    {
      id: 'SGT-02',
      plateNumber: 'GJ05CD5678',
      cameraId: 'CAM-08',
      cameraName: 'University Circle Outer',
      location: 'Gujarat University Navrangpura Circle, Ahmedabad',
      timestamp: '11 Sept 2026, 10:33 AM',
      detectionConfidence: 93,
      ocrConfidence: 90,
      trackingConfidence: 89,
      vehicleType: 'Luxury Sedan (Black)',
      speedKmh: 54,
      lane: 1,
      heading: 'South-East',
      evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'University Circle Outer', '11 Sept 2026, 10:33 AM', 'Sedan', '#1e293b', true),
    },
    {
      id: 'SGT-03',
      plateNumber: 'GJ05CD5678',
      cameraId: 'CAM-02',
      cameraName: 'Express Highway Toll Plaza',
      location: 'National Highway 48 Exit Toll, Ahmedabad',
      timestamp: '11 Sept 2026, 10:42 AM',
      detectionConfidence: 98,
      ocrConfidence: 96,
      trackingConfidence: 96,
      vehicleType: 'Luxury Sedan (Black)',
      speedKmh: 82,
      lane: 3,
      heading: 'Northbound Connector',
      evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'Express Highway Toll Plaza', '11 Sept 2026, 10:42 AM', 'Sedan', '#1e293b', true),
    },
    {
      id: 'SGT-04',
      plateNumber: 'GJ05CD5678',
      cameraId: 'CAM-03',
      cameraName: 'City Central Flyover',
      location: 'Paldi Cross Road Overbridge, Ahmedabad',
      timestamp: '11 Sept 2026, 11:03 AM',
      detectionConfidence: 97,
      ocrConfidence: 95,
      trackingConfidence: 94,
      vehicleType: 'Luxury Sedan (Black)',
      speedKmh: 61,
      lane: 2,
      heading: 'South towards Riverfront',
      evidenceUrl: generateEvidenceFrameSvg('GJ05CD5678', 'City Central Flyover', '11 Sept 2026, 11:03 AM', 'Sedan', '#1e293b', true),
    },
  ],
  'GJ01AB1234': [
    {
      id: 'SGT-11',
      plateNumber: 'GJ01AB1234',
      cameraId: 'CAM-05',
      cameraName: 'Riverfront Promenade North',
      location: 'Sabarmati Riverfront West Bank, Ahmedabad',
      timestamp: '11 Sept 2026, 10:12 AM',
      detectionConfidence: 92,
      ocrConfidence: 91,
      trackingConfidence: 90,
      vehicleType: 'Full-Size SUV (Green)',
      speedKmh: 45,
      lane: 1,
      heading: 'Southbound',
      evidenceUrl: generateEvidenceFrameSvg('GJ01AB1234', 'Riverfront Promenade North', '11 Sept 2026, 10:12 AM', 'SUV', '#047857', true),
    },
    {
      id: 'SGT-12',
      plateNumber: 'GJ01AB1234',
      cameraId: 'CAM-01',
      cameraName: 'Ring Road West Gate',
      location: 'Sarkhej-Gandhinagar Junction, Ahmedabad',
      timestamp: '11 Sept 2026, 10:45 AM',
      detectionConfidence: 96,
      ocrConfidence: 93,
      trackingConfidence: 95,
      vehicleType: 'Full-Size SUV (Green)',
      speedKmh: 72,
      lane: 3,
      heading: 'Eastbound Ring Road',
      evidenceUrl: generateEvidenceFrameSvg('GJ01AB1234', 'Ring Road West Gate', '11 Sept 2026, 10:45 AM', 'SUV', '#047857', true),
    },
  ],
  'MH02DJ9090': [
    {
      id: 'SGT-21',
      plateNumber: 'MH02DJ9090',
      cameraId: 'CAM-05',
      cameraName: 'Riverfront Promenade North',
      location: 'Sabarmati Riverfront West Bank, Ahmedabad',
      timestamp: '11 Sept 2026, 10:35 AM',
      detectionConfidence: 94,
      ocrConfidence: 91,
      trackingConfidence: 92,
      vehicleType: 'Compact Sedan (Silver)',
      speedKmh: 50,
      lane: 2,
      heading: 'Northbound',
      evidenceUrl: generateEvidenceFrameSvg('MH02DJ9090', 'Riverfront Promenade North', '11 Sept 2026, 10:35 AM', 'Sedan', '#64748b', false),
    },
  ],
};

// Route generation helper
export function getRoutePointsForPlate(plate: string, cameras: Camera[]): VehicleRoutePoint[] {
  const sightings = SIGHTINGS_BY_PLATE[plate.toUpperCase().replace(/\s+/g, '')] || [];
  return sightings.map((s, idx) => {
    const cam = cameras.find((c) => c.id === s.cameraId);
    return {
      order: idx + 1,
      cameraId: s.cameraId,
      cameraName: s.cameraName,
      location: s.location,
      latitude: cam ? cam.latitude : 23.0225 + idx * 0.01,
      longitude: cam ? cam.longitude : 72.5714 + idx * 0.01,
      timestamp: s.timestamp,
      plateConfidence: s.detectionConfidence,
      ocrConfidence: s.ocrConfidence,
      speedKmh: s.speedKmh,
    };
  });
}
